movie_rating_app/routes/auth.py
import functools
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from movie_rating_app import db
from movie_rating_app.controller.acess_user import *

bp = Blueprint("auth", __name__, url_prefix="/auth")


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("auth.login"))

        return view(**kwargs)

    return wrapped_view


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get("user_id")

    if user_id is None:
        g.user = None
    else:
        g.user = (
            get_user(user_id)
        )


@bp.route("/register", methods=("GET", "POST"))
def register():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        error = None

        if not username:
            error = "Username is required."
        elif not password:
            error = "Password is required."

        if error is None:
            try:
                user = User(username, generate_password_hash(password))
                store_user(user)
            except Exception:
                error = f"User {username} is already registered."
            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template("auth/register.html")


@bp.route("/login", methods=("GET", "POST"))
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        error = None
        user = get_user_by_username(username)

        if user is None:
            error = "Incorrect username."
        elif not check_password_hash(user.password_hash, password):
            error = "Incorrect password."

        if error is None:
            session.clear()
            session["user_id"] = user.id
            return redirect(url_for("index"))

        flash(error)

    return render_template("auth/login.html")


@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))

movie_rating_app/routes/movies.py
from operator import attrgetter
from flask import Blueprint
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for

from movie_rating_app.routes.auth import login_required
from movie_rating_app.models.movie import Movie
from movie_rating_app.controller.access_movies import *
from movie_rating_app.controller.access_movie_reactions import *
from movie_rating_app.controller.acess_user import *

bp = Blueprint("movies", __name__)


@bp.route("/")
def index(movies=None):
    user = g.user
    movies = movies or get_all_movies()
    sort_field = request.args.get('sort', 'date_of_publication')

    # Sort the list of items based on the chosen field
    sorted_movies = sorted(movies, key=attrgetter(sort_field), reverse=True)

    return render_template("index.html", movies=sorted_movies, current_user=user)


@bp.route("/user/<string:username>")
def movies_from_user(username):
    user = g.user
    movies = get_all_movies_for_user(username)
    return render_template("index.html", movies=movies, current_user=user)


@bp.route("/like/<int:id>")
@login_required
def toggle_like_movie(id):
    user = g.user
    movie = get_movie(id)

    reaction = get_user_reaction_for_movie(user, movie)
    if reaction is None:
        reaction = MovieReaction(user, movie, liked=True)
        store_movie_reaction(reaction)
    else:
        reaction.liked = not reaction.liked
        if reaction.liked:
            reaction.hated = False

        update_reaction(reaction)

    return redirect("/")


@bp.route("/hate/<int:id>")
@login_required
def toggle_hate_movie(id):
    user = g.user
    movie = get_movie(id)

    reaction = get_user_reaction_for_movie(user, movie)
    if reaction is None:
        reaction = MovieReaction(user, movie, hated=True)
        store_movie_reaction(reaction)
    else:
        reaction.hated = not reaction.hated
        if reaction.hated:
            reaction.liked = False
        update_reaction(reaction)
    return redirect("/")


@bp.route("/create", methods=("GET", "POST"))
@login_required
def create():
    if request.method == "POST":
        title = request.form["title"]
        description = request.form["description"]
        error = None

        if not title:
            error = "Title is required."

        if error is not None:
            flash(error)
        else:
            movie = Movie(title, description, g.user)
            store_movie(movie)
            return redirect(url_for("movies.index"))

    return render_template("/create.html")

movie_rating_app/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - MovieRama</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1><a href="{{ url_for('index') }}">MovieRama</a></h1>
  <ul>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

movie_rating_app/templates/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Movie{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="description">Description</label>
    <textarea name="description" id="description">{{ request.form['description'] }}</textarea>
    <input type="submit" value="Save">
  </form>
{% endblock %}

movie_rating_app/templates/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Movies{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('movies.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
<p>Sort by:
    <a href="{{ url_for('index', sort='likes_count') }}">Likes</a> |
    <a href="{{ url_for('index', sort='hates_count') }}">Hates</a> |
    <a href="{{ url_for('index', sort='date_of_publication') }}">Date</a>
</p>
  {% for movie in movies %}
  <article class="post">
    <header>
        <div>
            <h1>{{ movie.title }}</h1>
            <div class="about">by <a href="{{ url_for('movies.movies_from_user', username=movie.user.username)}}"> {{ movie.user.username }} </a> on {{movie.date_of_publication.strftime('%Y-%m-%d') }}</div>
        </div>
    </header>
    <p class="body">{{ movie.description }}</p>
    {% if current_user != movie.user %}
        <form method="GET" action="{{ url_for('movies.toggle_like_movie', id=movie.id) }}">
            <button class="like-button {% if movie in current_user.liked_movies %}liked-button{% endif %}"
                    {% if current_user and current_user.id == movie.user.id %}
                        disabled
                    {% endif %}>
                Like {{ movie.likes_count}}
            </button>
        </form>

        <form method="GET" action="{{ url_for('movies.toggle_hate_movie', id=movie.id) }}">
            <button class="like-button {% if movie in current_user.hated_movies %}hated-button{% endif %}"
                    {% if current_user and current_user.id == movie.user.id %}
                        disabled
                    {% endif %}>
                Hate {{ movie.hates_count}}
            </button>
        </form>
    {% endif %}
</article>
{% if not loop.last %}
      <hr>
{% endif %}
{% endfor %}
{% endblock %}